from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ExecutionStep:
    """Represents a single step in an execution plan."""

    step_id: str
    name: str
    tool: str
    arguments: dict[str, Any]
    status: str = "PENDING"  # PENDING, RUNNING, SUCCESS, FAILED
    result: Any = None
    error: str | None = None
    retries: int = 0
    max_retries: int = 2


@dataclass
class ExecutionPlan:
    """Represents a plan generated by the planner containing steps and dependencies."""

    plan_id: str
    steps: list[ExecutionStep] = field(default_factory=list)
    dependencies: dict[str, list[str]] = field(
        default_factory=dict
    )  # step_id -> list of prerequisite step_ids


@dataclass
class ExecutionResult:
    """Summary result of plan execution."""

    plan_id: str
    success: bool
    step_results: dict[str, Any] = field(default_factory=dict)
    error_message: str | None = None


class BaseAgent(ABC):
    """Abstract base class for all HospitalityAI autonomous agents."""

    name: str
    version: str
    description: str
    owner: str
    capabilities: list[str] = []
    required_tools: list[str] = []
    supported_workflows: list[str] = []
    status: str = "active"  # active, testing, deprecated

    def __init__(self) -> None:
        self.state = "UNINITIALIZED"

    async def initialize(self) -> None:
        """Prepares agent context and handles setup requirements."""
        self.state = "INITIALIZING"
        await self._on_initialize()
        self.state = "READY"

    async def plan(self, goal: str) -> ExecutionPlan:
        """Decomposes user target goals into dependency ordered steps."""
        self.state = "PLANNING"
        plan_obj = await self._on_plan(goal)
        return plan_obj

    async def execute(self, plan: ExecutionPlan) -> ExecutionResult:
        """Executes plan steps using available tools execution rules."""
        self.state = "EXECUTING"
        result = await self._on_execute(plan)
        return result

    async def validate(self, result: ExecutionResult) -> bool:
        """Verifies output integrity checks and schema correctness."""
        self.state = "VALIDATING"
        is_valid = await self._on_validate(result)
        return is_valid

    async def finalize(self) -> None:
        """Saves session checkpoints and clears execution caches."""
        self.state = "FINALIZING"
        await self._on_finalize()
        self.state = "TERMINATED"

    async def recover(self, error: Exception) -> bool:
        """Attempts recovery actions from execution errors."""
        self.state = "RECOVERING"
        recovered = await self._on_recover(error)
        if recovered:
            self.state = "READY"
        else:
            self.state = "FAILED"
        return recovered

    async def shutdown(self) -> None:
        """Gracefully releases resources and shutdowns connections."""
        await self._on_shutdown()
        self.state = "TERMINATED"

    # Hook implementations designed for subclasses overrides
    async def _on_initialize(self) -> None:
        """Initialize hook optionally overridden by subclass."""
        return None

    @abstractmethod
    async def _on_plan(self, goal: str) -> ExecutionPlan:
        pass

    @abstractmethod
    async def _on_execute(self, plan: ExecutionPlan) -> ExecutionResult:
        pass

    async def _on_validate(self, result: ExecutionResult) -> bool:
        """Validate hook optionally overridden by subclass."""
        return True

    async def _on_finalize(self) -> None:
        """Finalize hook optionally overridden by subclass."""
        return None

    async def _on_recover(self, error: Exception) -> bool:
        """Recover hook optionally overridden by subclass."""
        return False

    async def _on_shutdown(self) -> None:
        """Shutdown hook optionally overridden by subclass."""
        return None


__all__ = [
    "ExecutionStep",
    "ExecutionPlan",
    "ExecutionResult",
    "BaseAgent",
]
